# questions.py
# Nota: "R\\$ 300" escreve R\$ que o Streamlit renderiza como R$ sem formatar como LaTeX.
# O app.py converte R\$ → R$ antes de salvar no Excel.

FEMI_QUESTIONS = [
    {
        "id": "freq_compra",
        "texto": "Com que frequência você compra joias ou acessórios por ano?",
        "tipo": "single",
        "opcoes": ["Menos de 1 vez", "1–2 vezes", "3–5 vezes", "6 ou mais vezes"],
    },
    {
        "id": "faixa_de_renda_mensal",
        "texto": "Qual sua faixa de renda mensal?",
        "tipo": "single",
        "opcoes": [
            "Até R\\$ 3.000",
            "R\\$ 3.001 a R\\$ 6.000",
            "R\\$ 6.001 a R\\$ 12.000",
            "Acima de R\\$ 12.000",
        ],
    },
    {
        "id": "valor_ultima_compra",
        "texto": "Qual o valor médio da sua última compra de joia ou acessório?",
        "tipo": "single",
        "opcoes": [
            "Até R\\$ 300",
            "R\\$ 301 – R\\$ 800",
            "R\\$ 801 – R\\$ 2.000",
            "Acima de R\\$ 2.000",
        ],
    },
    {
        "id": "para_quem_compra",
        "texto": "Para quem você costuma comprar com mais frequência?",
        "tipo": "single",
        "opcoes": ["Para mim mesma", "Para presentear alguém", "Metade a metade"],
    },
    {
        "id": "onde_compra",
        "texto": "Onde você costuma comprar joias e acessórios? (até 2 opções)",
        "tipo": "multi",
        "max": 2,
        "opcoes": [
            "Shopping em Maceió",
            "Loja física de bairro",
            "Site ou app nacional (ex: Vivara, Oma)",
            "E-commerce importado (Shein, Shopee, Temu)",
            "Redes sociais ou WhatsApp de loja local",
        ],
    },
    {
        "id": "preocupacao_compra",
        "texto": "O que mais te preocupa ao comprar uma joia? (até 2 opções)",
        "tipo": "multi",
        "max": 2,
        "opcoes": [
            "Escurecer ou oxidar com o tempo",
            "Preço muito alto",
            "Design não combinar com meu estilo",
            "Falta de durabilidade",
            "Dificuldade de troca ou devolução",
        ],
    },
    {
        "id": "o_que_valoriza",
        "texto": "O que você mais valoriza ao escolher uma joia? (até 2 opções)",
        "tipo": "multi",
        "max": 2,
        "opcoes": [
            "Durabilidade",
            "Design exclusivo",
            "Preço acessível",
            "Marca conhecida",
            "Versatilidade para o dia a dia",
        ],
    },
    {
        "id": "estilo_preferido",
        "texto": "Qual estilo de joia você prefere?",
        "tipo": "single",
        "tem_outro": True,
        "opcoes": [
            "Clássico e atemporal",
            "Moderno e de tendência",
            "Depende da peça e da ocasião",
        ],
    },
    {
        "id": "compraria_online",
        "texto": "Você compraria uma joia online sem ver a peça fisicamente?",
        "tipo": "single",
        "opcoes": [
            "Sim, sem problema",
            "Sim, para peças simples",
            "Apenas se conhecer bem a loja",
            "Não, preciso ver e experimentar",
        ],
    },
    {
        "id": "lojas_conhece",
        "texto": "Quais lojas de joias de Maceió você conhece? (marque todas que conhecer)",
        "tipo": "multi",
        "max": 7,
        "tem_outro": True,
        "opcoes": [
            "Iolita",
            "RM Joias",
            "Vivara",
            "Vivante",
            "Arte Dourada",
            "Não conheço nenhuma",
        ],
    },
]

MASC_QUESTIONS = [
    {
        "id": "valor_ultimo_presente",
        "texto": "Qual o valor médio do seu último presente de joia ou acessório?",
        "tipo": "single",
        "opcoes": [
            "Até R\\$ 200",
            "R\\$ 201 a R\\$ 500",
            "R\\$ 501 a R\\$ 1.500",
            "Acima de R\\$ 1.500",
        ],
    },
    {
        "id": "onde_compra",
        "texto": "Onde você costuma comprar joias de presente ou para uso próprio? (até 2 opções)",
        "tipo": "multi",
        "max": 2,
        "opcoes": [
            "Shopping em Maceió",
            "Loja física de bairro",
            "Site ou app (ex: Vivara, Oma)",
            "E-commerce (Shein, Shopee, Temu)",
            "Redes sociais ou WhatsApp de loja local",
        ],
    },
    {
        "id": "preocupacao_presente",
        "texto": "O que mais te preocupa ao comprar uma joia de presente? (até 2 opções)",
        "tipo": "multi",
        "max": 2,
        "opcoes": [
            "A joia escurecer ou perder qualidade com o tempo",
            "Não saber o gosto dela",
            "Preço muito alto",
            "Não saber o tamanho certo",
            "Falta de variedade de modelos",
        ],
    },
    {
        "id": "ocasioes_compra",
        "texto": "Quais ocasiões mais motivam sua compra de presente? (até 3 opções)",
        "tipo": "multi",
        "max": 3,
        "opcoes": [
            "Aniversário dela",
            "Dia dos Namorados",
            "Natal",
            "Conquista ou vitória dela",
            "Impulso, sem ocasião especial",
            "Outras datas comemorativas",
        ],
    },
    {
        "id": "como_decide",
        "texto": "Como você costuma decidir qual joia comprar?",
        "tipo": "single",
        "opcoes": [
            "Ela me diz o que quer",
            "Pesquiso online e escolho sozinho",
            "Peço ajuda na loja",
            "Sigo o que ela usa habitualmente",
            "Peço sugestão a amigos ou família",
        ],
    },
    {
        "id": "o_que_valoriza",
        "texto": "O que você mais valoriza ao escolher uma joia de presente? (até 2 opções)",
        "tipo": "multi",
        "max": 2,
        "opcoes": [
            "Qualidade e durabilidade",
            "Preço acessível",
            "Design bonito",
            "Marca conhecida",
            "Embalagem e apresentação",
        ],
    },
    {
        "id": "compraria_online",
        "texto": "Você compraria uma joia online sem ver fisicamente?",
        "tipo": "single",
        "opcoes": [
            "Sim, sem problema",
            "Sim, para peças simples",
            "Apenas se conhecer bem a loja",
            "Não, prefiro ver pessoalmente",
        ],
    },
    {
        "id": "lojas_conhece",
        "texto": "Quais lojas de joias de Maceió você conhece? (marque todas que conhecer)",
        "tipo": "multi",
        "max": 7,
        "tem_outro": True,
        "opcoes": [
            "Iolita",
            "RM Joias",
            "Vivara",
            "Vivante",
            "Arte Dourada",
            "Não conheço nenhuma",
        ],
    },
    {
        "id": "preferencia_loja",
        "texto": "O que tornaria uma loja sua preferida para presentear? (até 2 opções)",
        "tipo": "multi",
        "max": 2,
        "opcoes": [
            "Variedade de modelos",
            "Atendimento consultivo (me ajuda a escolher)",
            "Embalagem especial para presente",
            "Preço e facilidade de parcelamento",
            "Facilidade de troca ou devolução",
        ],
    },
    {
        "id": "interesse_bolsas",
        "texto": "Além de joias, você teria interesse em presentear com bolsas de marca (ex: Coach)?",
        "tipo": "single",
        "opcoes": [
            "Sim, já faço isso",
            "Sim, teria interesse",
            "Talvez, dependendo do preço",
            "Não, prefiro joias",
            "Não costumo presentear com bolsas de marca",
        ],
    },
]